name: Regression
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!feature'
    tags:
      - '**'

  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'

jobs:
  start-runner:
    name: Start self-hosted ec2 runner
    runs-on: ubuntu-latest
  
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Start EC2 runner
        shell:
          aws ec2 start-instances --instance-id i-0b2d4c509fc3f1e3a

  run-benchmarks-on-runner:
    name: Make duckdb and generate benchmark data
    runs-on: self-hosted
    env:
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_TPCH: 1
      BUILD_TPCDS: 1
      BUILD_HTTPFS: 1
      BUILD_JEMALLOC: 1

    steps: 
      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build awscli cmake make python-is-python3 libssl-dev && pip install requests

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main

      - name: move duckdb-main to duckdb-old
        shell: bash
        run: |
          if [! -d ../duckdb-main]; then
            git clone git@github.com:duckdb/duckdb.git duckdb-main
            cd ../duckdb-main
            make 
            cd ..
          fi
          rm -rf duckdb-old
          mkdir -p duckdb-old
          cp -R duckdb-main/ duckdb-old

      - uses: actions/checkout@v4
        with:
          repository: 'duckdb/duckdb'
          path: 'duckdb-main'
          fetch-depth: 0

      - name: mount duckdb_benchmark_data to persistent storage
        shell: bash
        working-directory: duckdb-main
        run: |
          rm -rf duckdb_benchmark_data
          sudo mkfs -t xfs -f /dev/nvme1n1
          mkdir duckdb_benchmark_data
          sudo mount /dev/nvme1n1 duckdb_benchmark_data
          sudo chown -R ubuntu duckdb_benchmark_data

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Build
        shell: bash
        working-directory: duckdb-main
        run: |
          make clean
          make

      - name: Set up benchmarks
        shell: bash
        working-directory: duckdb-main
        run: |
          cp -r benchmark ../duckdb-old

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # aws s3 cp s3://duckdb-blobs/data/tpch-sf100.db tpch_sf1.duckdb 1> /dev/null
      # ln -s tpch_sf1.duckdb tpch_sf1_parquet.duckdb
      # ../build/release/duckdb -c tpch_sf1.duckdb "EXPORT DATABASE 'tpch_sf1_parquet' (FORMAT PARQUET);" 

      - name: Load data for sf 100 benchmarks
        working-directory: duckdb-main/duckdb_benchmark_data
        shell: bash
        run: |
          ../build/release/duckdb tpch_sf1.duckdb -c "call dbgen(sf=1); export database 'tpch_sf1_parquet' (FORMAT PARQUET);"

      - name: Regression Test TPCH
        working-directory: duckdb-main
        if: always()
        shell: bash
        run: |
          python scripts/regression_test_runner.py --old=../duckdb-old/build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/tpch.csv --verbose

      - name: Regression Test TPCH-PARQUET
        working-directory: duckdb-main
        if: always()
        shell: bash
        run: |
          python scripts/regression_test_runner.py --old=../duckdb-old/build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/tpch_parquet.csv --verbose

      - name: Regression Test H2OAI
        working-directory: duckdb-main
        if: always()
        shell: bash
        run: |
          python scripts/regression_test_runner.py --old=../duckdb-old/build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/h2oai.csv --verbose

      - name: shut down
        if: always()
        shell: bash
        run: sudo shutdown

  stop-ec2-runner:
    name: Turn off machine
    runs-on: ubuntu-latest
    needs:
      - start-runner # required to get output from the start-runner job
      - run-benchmarks-on-runner # required to wait when the main job is done

    steps:
      - name: Configure AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Stop machine
        if: always()
        shell: bash
        run: aws ec2 stop-instances --instance-ids i-0b2d4c509fc3f1e3a

